[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
viral_sync = "AeKT1B58Qi9rBtrtnMe11o4eXbVwHweKxGFNS5X3Vv46"

[programs.devnet]
viral_sync = "AeKT1B58Qi9rBtrtnMe11o4eXbVwHweKxGFNS5X3Vv46"

[programs.mainnet]
viral_sync = "AeKT1B58Qi9rBtrtnMe11o4eXbVwHweKxGFNS5X3Vv46"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm exec -- ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
