[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
viral_sync = "8D5chmUeb97oxykaBv7CTFpZnBotVAMnqYAvyk6qcQz9"

[programs.devnet]
viral_sync = "8D5chmUeb97oxykaBv7CTFpZnBotVAMnqYAvyk6qcQz9"

[programs.mainnet]
viral_sync = "8D5chmUeb97oxykaBv7CTFpZnBotVAMnqYAvyk6qcQz9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm exec -- ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
