[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
viral_sync = "D9ds2V6y4GFGKbo8wF8qQiF81dzhkiznmZsHepcSN6Ta"

[programs.devnet]
viral_sync = "D9ds2V6y4GFGKbo8wF8qQiF81dzhkiznmZsHepcSN6Ta"

[programs.mainnet]
viral_sync = "D9ds2V6y4GFGKbo8wF8qQiF81dzhkiznmZsHepcSN6Ta"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:anchor"
