import { existsSync, readFileSync } from 'fs';
import path from 'path';
import { PremiumButton, PremiumMetric, PremiumNav, PremiumShell, PremiumStatusBadge, PremiumSurface } from '@/components/premium/PremiumUi';

type Status = 'VERIFIED' | 'STALE' | 'MISSING' | 'SIMULATED' | 'READY';
type ProofArtifact = { ok?: boolean; proofStatus?: string; summary?: { blocked?: number; totalCases?: number }; verifiedFacts?: { verifierOk?: boolean }; status?: string; type?: string; kind?: string; generatedAt?: string; proofStatusNote?: string };
function load(file: string): ProofArtifact | null { const paths=[path.join(process.cwd(),'public','proofs',file),path.join(process.cwd(),'app','public','proofs',file)]; for(const p of paths){ if(existsSync(p)) try{return JSON.parse(readFileSync(p,'utf8')) as ProofArtifact;}catch{} } return null; }
function statusFrom(obj: ProofArtifact | null): Status { if(!obj) return 'MISSING'; const text=JSON.stringify(obj).toLowerCase(); if(/needs-regeneration|stale|unsafe|no-go/.test(text)) return 'STALE'; if(obj.ok===true || obj.proofStatus==='verified' || obj.summary?.blocked===obj.summary?.totalCases || obj.verifiedFacts?.verifierOk) return 'VERIFIED'; if(obj.status==='READY_FOR_FINAL_PROOF_RUN') return 'READY'; return 'SIMULATED'; }
function tone(status: Status): 'success'|'warning'|'danger'|'muted' { if(status==='VERIFIED') return 'success'; if(status==='READY'||status==='STALE') return 'warning'; if(status==='MISSING') return 'danger'; return 'muted'; }
const cards = [
  { title:'Live Proof', href:'/frontier-proof', file:'devnet-causal-commerce.json', detail:'Receipt, settlement, nullifier, intent hash, and verifier source.' },
  { title:'Fraud Gauntlet', href:'/frontier-gauntlet', file:'fraud-gauntlet.json', detail:'15 abuse cases showing how fake conversions get blocked.' },
  { title:'Conversion Orderbook', href:'/conversion-orderbook', file:'conversion-orderbook.json', detail:'Proof-backed campaign plus future CPA lanes.' },
  { title:'Merchant Passport', href:'/merchant-passport', file:'merchant-passport.json', detail:'Portable proof-of-local-commerce without customer data.' },
  { title:'Technical Deep Dive', href:'/technical-deep-dive', file:'invariant-matrix.json', detail:'POC-1, invariants, proof hashes, and auditor packet.' },
];
export default function FrontierPage(){ const loaded=cards.map(c=>({...c,obj:load(c.file)})); return <PremiumShell><PremiumNav/><section className="premium-proof-console"><div className="premium-proof-header"><div><span className="premium-eyebrow">Judge command center</span><h1 className="premium-proof-title">Proof-of-conversion for Solana commerce.</h1><p className="premium-lede">Merchants escrow rewards. Terminals and customers counter-attest conversions. Viral Sync settles only when the proof verifies.</p><div className="premium-actions"><PremiumButton href="/frontier-proof">Open live proof</PremiumButton><PremiumButton href="/frontier-gauntlet" variant="secondary">Replay the fraud</PremiumButton><PremiumButton href="/auditor-packet" variant="quiet">Auditor packet</PremiumButton></div></div><PremiumSurface tone="proof" className="premium-compact-proof-card"><div className="premium-card-title"><span>Category</span><h2>Outcome layer for Solana commerce</h2><p>Clicks are claims. Receipts are proof.</p></div></PremiumSurface></div><section className="premium-metrics compact"><PremiumMetric label="Core primitive" value="POC-1" detail="Proof-of-conversion receipt"/><PremiumMetric label="Entry point" value="/frontier" detail="One judge path"/><PremiumMetric label="Final run" value="frontier:final" detail="Nuclear proof command"/></section><section className="premium-gauntlet-list">{loaded.map(({title,href,detail,obj})=>{const st=statusFrom(obj); return <PremiumSurface key={title} tone="light" className="premium-gauntlet-case"><div><div className="premium-case-topline"><span>Command center card</span><PremiumStatusBadge tone={tone(st)}>{st}</PremiumStatusBadge></div><h2>{title}</h2><p>{detail}</p></div><div className="premium-gauntlet-evidence"><span>Artifact</span><code>{obj?.type??obj?.kind??'missing'}</code><small>{obj?.generatedAt??obj?.proofStatusNote??'Generate the artifact before final submission.'}</small><PremiumButton href={href} variant="secondary">Open</PremiumButton></div></PremiumSurface>})}</section></section></PremiumShell> }
