import { NextResponse } from 'next/server';
import { withSecurityHeaders } from '@/lib/launch/api';
import { getBackupDemoRecording, getBusinessQaBank, getExternalMockJudging, getFinalArchitectureVisuals, getFinalBugOnlyDay, getFinalLinkAudit, getFinalPitchDeckOutline, getFinalTechnicalDeepDive, getFinalVideoRecordingPlan, getFollowUpDemoReadiness, getHackathonPostmortem, getInvestorOnePager, getJudgeQaBank, getKnownLimitationsPage, getLiveDemoRehearsal, getMerchantFollowUpPacket, getNextMilestonePlan, getOneMerchantPosPilotPlan, getPostSubmissionAdapterSkeleton, getPostSubmissionOperatingPlan365, getPostSubmissionPaymentMatching, getPostSubmissionPosFailureHandling, getPostSubmissionPosPathChoice, getPostSubmissionReconciliationUi, getPostSubmissionWeeklyPosReview, getReleaseCandidateSnapshot, getRestabilizationPlan, getSecurityQaBank, getSubmissionDryRun, getSubmitPackageArchive, getTechnicalQaBank, getWeeklyAssetReviewFinal, getWeeklyFreezeReviewFinal, getWeeklyQaReview } from '@/lib/launch/server';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function GET() {
  return withSecurityHeaders(NextResponse.json({ ok: true, video: getFinalVideoRecordingPlan(), deepDive: getFinalTechnicalDeepDive(), deck: getFinalPitchDeckOutline(), visuals: getFinalArchitectureVisuals(), assets: getWeeklyAssetReviewFinal(), judgeQa: getJudgeQaBank(), technicalQa: getTechnicalQaBank(), businessQa: getBusinessQaBank(), securityQa: getSecurityQaBank(), rehearsal: getLiveDemoRehearsal(), mockJudging: getExternalMockJudging(), qaReview: getWeeklyQaReview(), releaseCandidate: getReleaseCandidateSnapshot(), backupDemo: getBackupDemoRecording(), links: getFinalLinkAudit(), limitations: getKnownLimitationsPage(), dryRun: getSubmissionDryRun(), bugOnly: getFinalBugOnlyDay(), freeze: getWeeklyFreezeReviewFinal(), submit: getSubmitPackageArchive(), followUp: getFollowUpDemoReadiness(), investor: getInvestorOnePager(), merchantFollowUp: getMerchantFollowUpPacket(), postmortem: getHackathonPostmortem(), milestone: getNextMilestonePlan(), restabilize: getRestabilizationPlan(), posPath: getPostSubmissionPosPathChoice(), adapter: getPostSubmissionAdapterSkeleton(), matching: getPostSubmissionPaymentMatching(), reconciliation: getPostSubmissionReconciliationUi(), posFailure: getPostSubmissionPosFailureHandling(), posPilot: getOneMerchantPosPilotPlan(), posReview: getPostSubmissionWeeklyPosReview(), operatingPlan: getPostSubmissionOperatingPlan365() }));
}
