import { existsSync, readFileSync } from 'fs';
import path from 'path';
import { PremiumButton, PremiumMetric, PremiumNav, PremiumShell, PremiumStatusBadge, PremiumSurface } from '@/components/premium/PremiumUi';

type Kit = { validationStatus?: string; merchantAlias?: string; validationKitHash?: string; rules?: string[]; interviewScript?: string[]; evidenceSlots?: Array<{ id?: string; status?: string; requiredForClaimingTraction?: boolean; prompt?: string }>; safeSubmissionWording?: string };
function loadJson<T>(candidates:string[], fallback:T):T{ for(const file of candidates){ if(!existsSync(file)) continue; try{return JSON.parse(readFileSync(file,'utf8')) as T;}catch{} } return fallback; }
function short(value?:unknown){ const text=String(value??'missing'); return text.length>24?`${text.slice(0,10)}…${text.slice(-8)}`:text; }
export default function MerchantValidationPage(){
 const kit=loadJson<Kit>([path.join(/* turbopackIgnore: true */ process.cwd(),'public','proofs','merchant-validation-kit.json'),path.join(/* turbopackIgnore: true */ process.cwd(),'app','public','proofs','merchant-validation-kit.json')],{validationStatus:'missing',evidenceSlots:[],rules:[],interviewScript:[]});
 const filled=(kit.evidenceSlots??[]).filter((slot)=>slot.status&&slot.status!=='empty').length;
 return <PremiumShell><PremiumNav />
  <section className="premium-proof-console"><div className="premium-proof-header"><div><span className="premium-eyebrow">Merchant validation kit</span><h1 className="premium-proof-title">Do not fake traction. Capture it cleanly.</h1><p className="premium-lede">This page is an honesty layer: it separates the verified devnet proof from any real-world merchant validation claims. Fill the evidence slots only with permissioned, real merchant feedback.</p><div className="premium-actions"><PremiumButton href="/frontier-proof">Proof first</PremiumButton><PremiumButton href="/conversion-orderbook" variant="secondary">Orderbook</PremiumButton><PremiumButton href="/merchant-passport" variant="quiet">Passport</PremiumButton></div></div><PremiumSurface tone="proof" className="premium-compact-proof-card"><div className="premium-card-title"><span>{kit.merchantAlias??'Merchant demo'}</span><h2>{kit.validationStatus??'missing'}</h2><p>Kit hash {short(kit.validationKitHash)}</p></div></PremiumSurface></div>
  <section className="premium-metrics compact"><PremiumMetric label="Evidence slots" value={`${filled}/${kit.evidenceSlots?.length??0}`} detail="Filled with permissioned evidence"/><PremiumMetric label="Traction claim" value={filled>0?'review manually':'not claimed'} detail="Do not overstate"/><PremiumMetric label="Safe wording" value="enabled" detail="Submission guardrail"/></section>
  <section className="premium-system-grid"><PremiumSurface tone="light" className="premium-system-section"><div className="premium-card-title"><span>Rules</span><h2>Validation without theater.</h2></div><ul className="premium-readiness-list">{(kit.rules??[]).map((rule)=><li key={rule}>{rule}</li>)}</ul></PremiumSurface><PremiumSurface tone="raised" className="premium-system-section"><div className="premium-card-title"><span>Interview script</span><h2>Ask better questions.</h2></div><ol className="premium-readiness-list">{(kit.interviewScript??[]).map((q)=><li key={q}>{q}</li>)}</ol></PremiumSurface></section>
  <section className="premium-gauntlet-list">{(kit.evidenceSlots??[]).map((slot)=><PremiumSurface key={slot.id} tone="light" className="premium-gauntlet-case"><div><div className="premium-case-topline"><span>{slot.id}</span><PremiumStatusBadge tone={slot.status==='empty'?'warning':'success'}>{slot.status??'empty'}</PremiumStatusBadge></div><h2>{slot.requiredForClaimingTraction?'Required to claim traction':'Optional evidence'}</h2><p>{slot.prompt}</p></div><div className="premium-gauntlet-evidence"><span>Submission rule</span><code>{slot.requiredForClaimingTraction?'Do not claim traction without this.':'Helpful but not required.'}</code></div></PremiumSurface>)}</section>
  <PremiumSurface tone="proof" className="premium-system-section"><div className="premium-card-title"><span>Safe submission wording</span><h2>{kit.safeSubmissionWording??'Generate merchant-validation-kit.json.'}</h2></div></PremiumSurface>
  </section></PremiumShell>;
}
