import { copyFileSync, cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from 'fs';
import path from 'path';
import { execFileSync } from 'child_process';

const backupRoot = path.resolve('tmp/mock-final-backup');
const mockOut = path.resolve('dist/mock-final');
const proofRoot = path.resolve('app/public/proofs');
const docsRoot = path.resolve('docs');
const auditorRoot = path.resolve('dist/auditor-packet');
const tmpVerifier = path.resolve('tmp/devnet-causal-commerce-verifier.json');

function runScript(script: string, env: Record<string, string> = {}) {
  execFileSync(process.execPath, ['-r', 'ts-node/register/transpile-only', script], {
    stdio: 'inherit',
    env: {
      ...process.env,
      ...env,
      ALLOW_MOCK_FINAL: '1',
      MOCK_FINAL: '1',
    },
  });
}

function backup() {
  rmSync(backupRoot, { recursive: true, force: true });
  mkdirSync(backupRoot, { recursive: true });

  if (existsSync(proofRoot)) {
    cpSync(proofRoot, path.join(backupRoot, 'proofs'), { recursive: true });
  }
  if (existsSync(docsRoot)) {
    cpSync(docsRoot, path.join(backupRoot, 'docs'), { recursive: true });
  }
  if (existsSync(auditorRoot)) {
    cpSync(auditorRoot, path.join(backupRoot, 'auditor-packet'), { recursive: true });
  }

  if (existsSync(tmpVerifier)) {
    mkdirSync(path.join(backupRoot, 'tmp'), { recursive: true });
    copyFileSync(tmpVerifier, path.join(backupRoot, 'tmp/devnet-causal-commerce-verifier.json'));
  }
}

function restore() {
  rmSync(proofRoot, { recursive: true, force: true });
  if (existsSync(path.join(backupRoot, 'proofs'))) {
    cpSync(path.join(backupRoot, 'proofs'), proofRoot, { recursive: true });
  }

  if (existsSync(path.join(backupRoot, 'tmp/devnet-causal-commerce-verifier.json'))) {
    mkdirSync(path.resolve('tmp'), { recursive: true });
    copyFileSync(path.join(backupRoot, 'tmp/devnet-causal-commerce-verifier.json'), tmpVerifier);
  } else if (existsSync(tmpVerifier)) {
    rmSync(tmpVerifier, { force: true });
  }

  rmSync(docsRoot, { recursive: true, force: true });
  if (existsSync(path.join(backupRoot, 'docs'))) {
    cpSync(path.join(backupRoot, 'docs'), docsRoot, { recursive: true });
  }

  rmSync(auditorRoot, { recursive: true, force: true });
  if (existsSync(path.join(backupRoot, 'auditor-packet'))) {
    cpSync(path.join(backupRoot, 'auditor-packet'), auditorRoot, { recursive: true });
  }
}

try {
  backup();

  mkdirSync(path.resolve('tmp'), { recursive: true });
  mkdirSync(proofRoot, { recursive: true });
  copyFileSync(
    path.resolve('fixtures/mock-final/devnet-causal-commerce.json'),
    path.resolve('app/public/proofs/devnet-causal-commerce.json'),
  );
  copyFileSync(
    path.resolve('fixtures/mock-final/devnet-causal-commerce-verifier.json'),
    path.resolve('tmp/devnet-causal-commerce-verifier.json'),
  );

  runScript('scripts/check-program-id-consistency.ts');
  runScript('scripts/publish-verifier.ts');
  runScript('scripts/generate-merchant-passport.ts');
  runScript('scripts/generate-fraud-gauntlet.ts');
  runScript('scripts/generate-conversion-orderbook.ts');
  runScript('scripts/generate-campaign-links.ts');
  runScript('scripts/generate-merchant-validation-kit.ts');
  runScript('scripts/generate-proof-feed.ts');
  runScript('scripts/generate-invariant-matrix.ts');
  runScript('scripts/generate-frontier-readiness.ts');
  runScript('scripts/stamp-proof-artifacts.ts');
  runScript('scripts/validate-proof-schemas.ts', { PROOF_SCHEMA_FINAL: '1' });
  runScript('scripts/prepare-frontier-submission.ts');
  runScript('scripts/generate-auditor-packet.ts');
  runScript('scripts/assert-no-stale-artifacts.ts', { ALLOW_MOCK_FINAL: '1' });

  rmSync(mockOut, { recursive: true, force: true });
  mkdirSync(mockOut, { recursive: true });
  cpSync(proofRoot, path.join(mockOut, 'proofs'), { recursive: true });
  cpSync(path.resolve('docs'), path.join(mockOut, 'docs'), { recursive: true });
  if (existsSync(auditorRoot)) {
    cpSync(auditorRoot, path.join(mockOut, 'auditor-packet'), { recursive: true });
  }
  writeFileSync(
    path.join(mockOut, 'README.md'),
    [
      '# Mock Final Pipeline Output',
      '',
      'This folder is generated by frontier:mock-final.',
      'It is not submission proof and must never be used as final evidence.',
      '',
    ].join('\n'),
  );

  console.log(JSON.stringify({ ok: true, mode: 'mock-final', output: 'dist/mock-final' }, null, 2));
} finally {
  restore();
}
